params = dict()

params['data'] = '~/Downloads/rgbd_dataset_freiburg3_long_office_household/rgb/1341847989.334871.png'
params['pretrained'] = False#'./model/GCNv2.pth'
params['save_path'] = './save/1341847989.334871.png'
params['imagepath'] = '../img/'
params['keypoint'] = './data_keypoint/'
params['gt'] = './gt/'
params['batch_size'] = 128
params['num_work'] = 8
params['gpu'] = [1,2,3,4,5,6,7]
params['c'] = 8
params['learning_rate'] = 1e-4
params['num_epoch'] = 500
params['model_path'] = './model/GCNv2.pth'
params['random drop'] = 0
params['cal_match'] = True
params['log']  = './log/loss.txt'
params['margin'] = 0.5
